### PR TITLE
Migrate next branch to the Terra repository

### PR DESCRIPTION
**Pull request by pieckenst**
It might be a bit too early for it , but since you did put up the f37-experimental branch , i felt like pull requesting a similar thing to next

### CODE REVIEW

**Comment by pieckenst** [comment]
@electricduck , i hope this might be mergable in

**Comment by electricduck** [comment]
Appreciate the merge, however
* Terra does not have a `38` repository yet, so we'd have to hardcode `38` in `terra.repo` and this is something I'm only willing to do after the next release of Sodalite: the `release/` branches are already starting to have major disparity with each other, which we should be avoiding.
* I was in the middle of refactoring some stuff making automatic merging potentially dangerous.

Don't let that put you off future PRs though :smiley:

**Comment by pieckenst** [comment]
I see :) well my pull request also pulled in stuff from main so next would get a bit more parity too

**Comment by pieckenst** [comment]
but i guess i can do that with separate pr

**Pull request closed without merging**
